# Generated by Django 6.0.4 on 2026-04-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugAndSupplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("vitamin", "Vitamin"),
                            ("antibiotics", "Antibiotics"),
                            ("vaccine", "Vaccine"),
                            ("electrolyte", "Electrolyte"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_dosage_unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement for this product e.g. ml, g, stachets, vials",
                        max_length=50,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("layers_mash", "Layer Mash"),
                            ("broiler_starter", "Broiler Starter"),
                            ("broiler_finisher", "Broiler Finisher"),
                            ("grower_mash", "Grower Mash"),
                            ("other", "other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "suuplier_type",
                    models.CharField(
                        choices=[
                            ("feed", "Feed"),
                            ("birds", "Birds"),
                            ("drugs", "Drugs"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[("layer", "Layer"), ("broiler", "Broiler")],
                        max_length=20,
                    ),
                ),
                ("initial_count", models.PositiveIntegerField()),
                (
                    "current_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("date_placed", models.DateField()),
                ("date_removed", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flocks",
                        to="core.pen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_received", models.PositiveIntegerField()),
                ("cost_per_bird", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                ("placement_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "flock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement",
                        to="core.flock",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements_recorded",
                        to="core.worker",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements_recorded",
                        to="core.supplier",
                    ),
                ),
            ],
        ),
    ]
