# Generated by Django 6.0.4 on 2026-04-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="suuplier_type",
            new_name="supplier_type",
        ),
    ]
