# Generated by Django 6.0.4 on 2026-04-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_drugandsupplement_feedtype_supplier_flock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField()),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier invoice or waybill reference for this delivery trip",
                        max_length=100,
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "delivery_confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries_confirmed",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_received", models.PositiveIntegerField()),
                ("quantity_rejected", models.PositiveIntegerField(default=0)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Explain why bags were rejected if any"
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.feeddelivery",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_items",
                        to="core.feedtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedProcurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partially_delivered", "Partially Delivered"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_orders_placed",
                        to="core.worker",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_procurements",
                        to="core.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Transfer"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of supplier representative who received payment",
                        max_length=200,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Receipt or transaction reference number",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_payments_made",
                        to="core.worker",
                    ),
                ),
                (
                    "procurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.feedprocurement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feeddelivery",
            name="procurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="core.feedprocurement",
            ),
        ),
        migrations.CreateModel(
            name="FeedProcurementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_ordered", models.PositiveIntegerField()),
                (
                    "bag_size_kg",
                    models.PositiveIntegerField(
                        help_text="Weight of each bag in kilograms e.g. 25 or 50"
                    ),
                ),
                ("price_per_bag", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_items",
                        to="core.feedtype",
                    ),
                ),
                (
                    "procurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.feedprocurement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_balance",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Auto-updated by system on every stock movement",
                    ),
                ),
                (
                    "reorder_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum number of bags before a low stock alert is triggered",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "feed_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock",
                        to="core.feedtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "IN"), ("out", "OUT")], max_length=3
                    ),
                ),
                (
                    "movement_reason",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("issuance", "Issuance"),
                            ("adjustment", "Adjustment"),
                            ("damaged", "Damaged"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Stock balance immediately after this movement — set automatically",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("delivery", "Delivery"),
                            ("issuance", "Issuance"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the linked Delivery or Issuance record",
                        null=True,
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True,
                        help_text="Required when movement reason is Adjustment",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for Adjustment movements",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments_authorized",
                        to="core.worker",
                    ),
                ),
                (
                    "feed_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="core.feedstock",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
    ]
