# Generated by Django 6.0.4 on 2026-04-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feeddelivery_feeddeliveryitem_feedprocurement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cleaning_date", models.DateField()),
                (
                    "cleaning_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("saturday_deep_clean", "Saturday Deep Clean"),
                        ],
                        max_length=25,
                    ),
                ),
                ("swept", models.BooleanField(default=False)),
                ("general_tidying_done", models.BooleanField(default=False)),
                ("gutter_cleared", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Supervisor remarks — especially important if status is Rejected",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleaning_logs_confirmed",
                        to="core.worker",
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleaning_logs",
                        to="core.pen",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleaning_logs_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drug_orders_authorized",
                        to="core.worker",
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drug_orders_made",
                        to="core.worker",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drug_purchase_orders",
                        to="core.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugPurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_purchased",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_unit",
                    models.CharField(
                        help_text="e.g. ml, g, sachets, vials", max_length=50
                    ),
                ),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Computed: quantity_purchased x cost_per_unit",
                        max_digits=12,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date on this specific batch",
                        null=True,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier batch reference for traceability",
                        max_length=100,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="core.drugandsupplement",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.drugpurchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Auto-updated by system on every stock movement",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(
                        help_text="e.g. ml, g, sachets, vials", max_length=50
                    ),
                ),
                (
                    "reorder_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum quantity before low stock alert is triggered",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "drug",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock",
                        to="core.drugandsupplement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "IN"), ("out", "OUT")], max_length=3
                    ),
                ),
                (
                    "movement_reason",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("administration", "Administration"),
                            ("expired", "Expired"),
                            ("damaged", "Damaged"),
                            ("adjustment", "Adjustment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Balance immediately after this movement — set automatically",
                        max_digits=10,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drug_purchase", "Drug Purchase"),
                            ("water_treatment", "Water Treatment"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the linked Drug Purchase or Water Treatment record",
                        null=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of this batch — relevant for IN movements",
                        null=True,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer batch code printed on product packaging",
                        max_length=100,
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True,
                        help_text="Required if movement reason is Adjustment",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for Adjustment and Expired movements",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drug_adjustments_authorized",
                        to="core.worker",
                    ),
                ),
                (
                    "drug_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="core.drugstock",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drug_movements_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EggCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_date", models.DateField()),
                (
                    "observed_count",
                    models.PositiveIntegerField(
                        help_text="Raw egg count inside the pen at point of collection"
                    ),
                ),
                (
                    "observed_at",
                    models.TimeField(
                        help_text="Time collection happened inside the pen"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_collections",
                        to="core.worker",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_collections",
                        to="core.flock",
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_collections",
                        to="core.pen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EggGrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whole_eggs", models.PositiveIntegerField()),
                ("broken_eggs", models.PositiveIntegerField(default=0)),
                ("dirty_eggs", models.PositiveIntegerField(default=0)),
                (
                    "total_graded",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: whole + broken + dirty — set automatically",
                    ),
                ),
                (
                    "grading_discrepancy",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: total_graded minus observed_count — set automatically",
                    ),
                ),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grading",
                        to="core.eggcollection",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_gradings",
                        to="core.worker",
                    ),
                ),
                (
                    "support_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_grading_support",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EggStorageConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whole_eggs_stored", models.PositiveIntegerField()),
                ("broken_eggs_stored", models.PositiveIntegerField(default=0)),
                (
                    "total_stored",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: sum of all stored counts — set automatically",
                    ),
                ),
                (
                    "storage_discrepancy",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: total_graded minus total_stored — set automatically",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_storage_confirmations",
                        to="core.worker",
                    ),
                ),
                (
                    "grading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_confirmation",
                        to="core.egggrading",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EggTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("whole_eggs", models.PositiveIntegerField()),
                ("broken_eggs", models.PositiveIntegerField(default=0)),
                (
                    "total_eggs",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: sum of all three — set automatically",
                    ),
                ),
                (
                    "received_by",
                    models.CharField(
                        help_text="Name of sales branch representative who received",
                        max_length=200,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "transferred_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_transfers",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedIssuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuance_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_issuances",
                        to="core.flock",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_issuances_made",
                        to="core.worker",
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_issuances",
                        to="core.pen",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_issuances_received",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedIssuanceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bags_issued", models.PositiveIntegerField()),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance_items",
                        to="core.feedtype",
                    ),
                ),
                (
                    "issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.feedissuance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceFault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fault_type",
                    models.CharField(
                        choices=[
                            ("wire_mesh", "Wire Mesh"),
                            ("nipple_drinker", "Nipple Drinker"),
                            ("trough", "Trough"),
                            ("frame", "Cage Frame"),
                            ("latch", "Latch or Door"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fault_description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("urgent", "Urgent"), ("minor", "Minor")],
                        max_length=10,
                    ),
                ),
                ("reported_date", models.DateField()),
                (
                    "observed_at",
                    models.TimeField(
                        help_text="Time worker physically noticed the fault"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_faults",
                        to="core.pen",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faults_reported",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("repair_date", models.DateField(blank=True, null=True)),
                ("repair_description", models.TextField(blank=True)),
                ("materials_used", models.TextField(blank=True)),
                (
                    "repair_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "is_temporary_fix",
                    models.BooleanField(
                        default=False,
                        help_text="If checked the fault stays open until a permanent repair is recorded",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs_assigned_by",
                        to="core.worker",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs_assigned",
                        to="core.worker",
                    ),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs_authorized",
                        to="core.worker",
                    ),
                ),
                (
                    "fault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs",
                        to="core.maintenancefault",
                    ),
                ),
                (
                    "repaired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs_carried_out",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_date", models.DateField()),
                ("drying_done", models.BooleanField(default=False)),
                ("date_dried", models.DateField(blank=True, null=True)),
                ("bags_filled", models.PositiveIntegerField(blank=True, null=True)),
                ("bags_sold", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "price_per_bag",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Computed: bags_sold x price_per_bag — set automatically",
                        max_digits=12,
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                ("payment_received", models.BooleanField(default=False)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manure_collected",
                        to="core.worker",
                    ),
                ),
                (
                    "dried_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manure_dried",
                        to="core.worker",
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manure_logs",
                        to="core.pen",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manure_logs_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortalityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_found", models.DateField()),
                (
                    "observed_at",
                    models.TimeField(
                        help_text="Time worker physically found the dead birds"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "total_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: sum of all MortalityRecordItem counts — set automatically",
                    ),
                ),
                (
                    "is_high_mortality",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Set automatically when total_count exceeds threshold",
                    ),
                ),
                ("alert_sent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "discovered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortalities_discovered",
                        to="core.worker",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_records",
                        to="core.flock",
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_records",
                        to="core.pen",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortalities_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortalityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_date", models.DateField(auto_now_add=True)),
                (
                    "threshold_exceeded",
                    models.PositiveIntegerField(
                        help_text="The count that triggered this alert"
                    ),
                ),
                (
                    "notified_persons",
                    models.TextField(
                        help_text="List everyone who was informed — manager, owner, vet"
                    ),
                ),
                (
                    "response_action",
                    models.CharField(
                        choices=[
                            ("vet_called", "Vet Called"),
                            ("pen_inspected", "Pen Inspected"),
                            ("feed_checked", "Feed Checked"),
                            ("water_checked", "Water Checked"),
                            ("birds_isolated", "Birds Isolated"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "notified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_alerts_sent",
                        to="core.worker",
                    ),
                ),
                (
                    "response_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_alerts_actioned",
                        to="core.worker",
                    ),
                ),
                (
                    "mortality_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alert",
                        to="core.mortalityrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortalityRecordItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("fresh", "Fresh"),
                            ("decomposed", "Decomposed"),
                            ("injured", "Injured"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("buried", "Buried"),
                            ("burned", "Burned"),
                            ("pit", "Pit"),
                            ("sold", "Sold"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sale_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount received if disposal method is Sold",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True,
                        help_text="Who bought the birds if disposal method is Sold",
                        max_length=200,
                    ),
                ),
                (
                    "suspected_cause",
                    models.CharField(
                        choices=[
                            ("starvation", "Starvation"),
                            ("disease", "Disease"),
                            ("injury", "Injury"),
                            ("unknown", "Unknown"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mortality_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.mortalityrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PenFeedingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeding_date", models.DateField()),
                ("leftover_observed", models.BooleanField(default=False)),
                (
                    "leftover_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("added_on_top", "Added on Top"),
                            ("removed_first", "Removed First"),
                            ("reduced_ration", "Reduced Ration"),
                            ("nothing_done", "Nothing Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "fed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_activities",
                        to="core.worker",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_activities",
                        to="core.flock",
                    ),
                ),
                (
                    "issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_activities",
                        to="core.feedissuance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PenFeedingActivityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bags_used", models.PositiveIntegerField()),
                ("empty_bags_returned", models.PositiveIntegerField(default=0)),
                (
                    "bags_discrepancy",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Computed: bags_used minus empty_bags_returned — set automatically",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_activity_items",
                        to="core.feedtype",
                    ),
                ),
                (
                    "feeding_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.penfeedingactivity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PenFeedingSupervision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distribution_even", models.BooleanField(default=False)),
                (
                    "trough_condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("damaged", "Damaged"),
                            ("needs_attention", "Needs Attention"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bird_behavior",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("not_eating", "Not Eating"),
                            ("lethargic", "Lethargic"),
                            ("aggressive", "Aggressive"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("flagged", "Flagged"),
                            ("rejected", "Rejected"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("supervised_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "feeding_activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervision",
                        to="core.penfeedingactivity",
                    ),
                ),
                (
                    "supervised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_supervisions",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterTreatmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treatment_date", models.DateField()),
                (
                    "is_plain_water",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if no drug or supplement was added",
                    ),
                ),
                (
                    "dosage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ml", "ml"),
                            ("g", "g"),
                            ("sachets", "Sachets"),
                            ("vials", "Vials"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adjusted_dosage",
                    models.BooleanField(
                        default=False, help_text="Check if standard dosage was adjusted"
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True, help_text="Required if dosage was adjusted"
                    ),
                ),
                (
                    "substitute_authorization",
                    models.BooleanField(
                        default=False,
                        help_text="Check if a substitute authorized in the manager's absence",
                    ),
                ),
                (
                    "observed_at",
                    models.TimeField(
                        help_text="Time treatment was physically administered"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_treatments_administered",
                        to="core.worker",
                    ),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Farm manager who approved — not required for plain water",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_treatments_authorized",
                        to="core.worker",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_treatments",
                        to="core.drugandsupplement",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_treatments",
                        to="core.flock",
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_treatments",
                        to="core.pen",
                    ),
                ),
            ],
        ),
    ]
