# Generated by Django 6.0.4 on 2026-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_worker_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="drugstockmovement",
            name="movement_reason_other",
            field=models.CharField(
                blank=True,
                help_text="Describe movement reason if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="feedstockmovement",
            name="movement_reason_other",
            field=models.CharField(
                blank=True,
                help_text="Describe movement reason if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="maintenancefault",
            name="fault_type_other",
            field=models.CharField(
                blank=True,
                help_text="Describe fault type if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mortalityalert",
            name="response_action_other",
            field=models.CharField(
                blank=True,
                help_text="Describe response action if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mortalityrecorditem",
            name="disposal_method_other",
            field=models.CharField(
                blank=True,
                help_text="Describe disposal method if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mortalityrecorditem",
            name="suspected_cause_other",
            field=models.CharField(
                blank=True,
                help_text="Describe suspected cause if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="penfeedingsupervision",
            name="bird_behavior_other",
            field=models.CharField(
                blank=True,
                help_text="Describe bird behavior if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_type_other",
            field=models.CharField(
                blank=True,
                help_text="Describe supplier type if you selected Other above",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="watertreatmentlog",
            name="dosage_unit_other",
            field=models.CharField(
                blank=True,
                help_text="Specify dosage unit if you selected Other above",
                max_length=100,
            ),
        ),
    ]
