# Generated by Django 6.0.4 on 2026-05-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_drugstockmovement_movement_reason_other_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("wholesale", "Wholesale"),
                            ("retail", "Retail"),
                            ("both", "Both"),
                        ],
                        default="wholesale",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("egg", "Egg"),
                            ("drug", "Drug / Supplement"),
                            ("feed", "Feed"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g. crate, bag, bottle, sachet", max_length=50
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "retail_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "wholesale_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum quantity to qualify for wholesale price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="OldLayerSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField()),
                ("quantity_sold", models.PositiveIntegerField()),
                (
                    "price_per_bird",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Bank Transfer"),
                            ("pos", "POS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="old_layer_sales",
                        to="core.flock",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="old_layer_sales_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopOutflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outflow_date", models.DateField()),
                (
                    "outflow_type",
                    models.CharField(
                        choices=[
                            ("cash_withdrawal", "Cash Withdrawal"),
                            ("salary", "Salary Payment"),
                            ("restock", "External Restock Payment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_to", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_outflows_authorized",
                        to="core.worker",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_outflows_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name_walkin",
                    models.CharField(
                        blank=True,
                        help_text="Name for walk-in customers not in the system",
                        max_length=200,
                    ),
                ),
                ("sale_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("wholesale", "Wholesale"), ("retail", "Retail")],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Bank Transfer"),
                            ("pos", "POS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Transfer reference or POS receipt number",
                        max_length=200,
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Has the product been delivered to the customer",
                    ),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for walk-in customers",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_sales",
                        to="core.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="core.shopproduct",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_sales_recorded",
                        to="core.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "reorder_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock",
                        to="core.shopproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "Stock In"), ("out", "Stock Out")],
                        max_length=10,
                    ),
                ),
                (
                    "movement_reason",
                    models.CharField(
                        choices=[
                            ("farm_delivery", "Farm Delivery"),
                            ("external_purchase", "External Purchase"),
                            ("sale", "Sale"),
                            ("adjustment", "Adjustment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_stock_movements",
                        to="core.worker",
                    ),
                ),
                (
                    "shop_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="core.shopstock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("transfer", "Bank Transfer")],
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salaries_paid",
                        to="core.worker",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salaries",
                        to="core.worker",
                    ),
                ),
            ],
            options={
                "unique_together": {("worker", "month", "year")},
            },
        ),
    ]
