# Generated by Django 6.0.4 on 2026-05-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_shopproduct_oldlayersale_shopoutflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="role",
            field=models.CharField(
                choices=[
                    ("pen_workers", "Pen Worker"),
                    ("supervisor", "Supervisor"),
                    ("store_keeper", "Store Keeper"),
                    ("manager", "Farm Mamager"),
                    ("general_manager", "General Manager"),
                    ("salesperson", "Salesperson"),
                    ("accountant", "Accountant"),
                    ("director", "Director"),
                ],
                max_length=50,
            ),
        ),
    ]
