# Generated by Django 6.0.4 on 2026-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_worker_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopsale",
            name="delivered",
        ),
        migrations.AddField(
            model_name="shopsale",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                    ("complete", "Complete"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shopsale",
            name="quantity_delivered",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="How much has been delivered so far",
                max_digits=10,
            ),
        ),
    ]
