# Generated by Django 6.0.4 on 2026-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_shopdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="egg_grade",
            field=models.CharField(
                choices=[
                    ("jumbo", "Jumbo"),
                    ("normal", "Normal"),
                    ("new_drop", "New Drop"),
                    ("cracked", "Cracked"),
                    ("not_applicable", "Not Applicable"),
                ],
                default="not_applicable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shopsale",
            name="quantity_delivered_at_sale",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="How much was taken at point of sale",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="shopsale",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                    ("complete", "Complete"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shopsale",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="shopsale",
            name="quantity_delivered",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Auto computed from delivery records",
                max_digits=10,
            ),
        ),
    ]
