# Generated by Django 6.0.4 on 2026-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_shopproduct_egg_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopsale",
            name="quantity_delivered",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Auto computed from delivery records",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="shopsale",
            name="quantity_delivered_at_sale",
            field=models.IntegerField(
                default=0, help_text="How much was taken at point of sale"
            ),
        ),
    ]
