# Generated by Django 6.0.4 on 2026-05-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_shopsale_quantity_delivered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopsale",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="delivery_status",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="price_per_unit",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="pricing_type",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="quantity_delivered",
        ),
        migrations.RemoveField(
            model_name="shopsale",
            name="quantity_delivered_at_sale",
        ),
        migrations.AlterField(
            model_name="shopsale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Computed from all sale items",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="ShopSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        default="wholesale", editable=False, max_length=20
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "quantity_delivered_at_sale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="How much was taken at point of sale",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_delivered",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("complete", "Complete"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="core.shopproduct",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.shopsale",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="shopdelivery",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="core.shopsaleitem",
            ),
        ),
    ]
