# Generated by Django 6.0.4 on 2026-05-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_shopsale_delivery_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopdelivery",
            old_name="sale",
            new_name="sale_item",
        ),
    ]
