# Generated by Django 6.0.4 on 2026-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_sale_shopdelivery_sale_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsale",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                    ("complete", "Complete"),
                ],
                default="pending",
                editable=False,
                help_text="Auto-computed from all item delivery statuses",
                max_length=20,
            ),
        ),
    ]
