# Generated by Django 6.0.4 on 2026-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_shopsaleitem_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost price per unit for profit calculation",
                max_digits=10,
            ),
        ),
    ]
