# Generated by Django 6.0.4 on 2026-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_shopproduct_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsaleitem",
            name="cost_price_per_unit",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="shopsaleitem",
            name="profit_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="shopstock",
            name="current_batch_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shopstock",
            name="current_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopstockmovement",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="Batch number for stock-in movements",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="shopstockmovement",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="Expiry date for stock-in movements", null=True
            ),
        ),
        migrations.AddField(
            model_name="shopstockmovement",
            name="manufacture_date",
            field=models.DateField(
                blank=True,
                help_text="Manufacture date for stock-in movements",
                null=True,
            ),
        ),
    ]
